apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: msginservice
  name: k8smsginservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: k8smsginservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8smsginservice
    spec:
      containers:
      - image: rameshsubramani/messagespark:latest
        name: k8smsginservice
        ports:
        - containerPort: 8083
